[package]
name = "vcs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = { version = "0.4", features = ["serde"] }
sha1 = "0.10"
